//go:build go1.18
// +build go1.18

// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See License.txt in the project root for license information.
// Code generated by Microsoft (R) AutoRest Code Generator. DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package backup

// ClientBeginFullBackupOptions contains the optional parameters for the Client.BeginFullBackup method.
type ClientBeginFullBackupOptions struct {
	// Resumes the LRO from the provided token.
	ResumeToken string
}

// ClientBeginFullRestoreOptions contains the optional parameters for the Client.BeginFullRestore method.
type ClientBeginFullRestoreOptions struct {
	// Resumes the LRO from the provided token.
	ResumeToken string
}

// ClientBeginSelectiveKeyRestoreOptions contains the optional parameters for the Client.BeginSelectiveKeyRestore method.
type ClientBeginSelectiveKeyRestoreOptions struct {
	// Resumes the LRO from the provided token.
	ResumeToken string
}
