// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See License.txt in the project root for license information.
// Code generated by Microsoft (R) Go Code Generator. DO NOT EDIT.

package azsecrets

// KeyVaultClientBackupSecretOptions contains the optional parameters for the KeyVaultClient.BackupSecret method.
type KeyVaultClientBackupSecretOptions struct {
	// placeholder for future optional parameters
}

// KeyVaultClientDeleteSecretOptions contains the optional parameters for the KeyVaultClient.DeleteSecret method.
type KeyVaultClientDeleteSecretOptions struct {
	// placeholder for future optional parameters
}

// KeyVaultClientGetDeletedSecretOptions contains the optional parameters for the KeyVaultClient.GetDeletedSecret method.
type KeyVaultClientGetDeletedSecretOptions struct {
	// placeholder for future optional parameters
}

// KeyVaultClientGetDeletedSecretsOptions contains the optional parameters for the KeyVaultClient.NewGetDeletedSecretsPager
// method.
type KeyVaultClientGetDeletedSecretsOptions struct {
	// Maximum number of results to return in a page. If not specified the service
	// will return up to 25 results.
	Maxresults *int32
}

// KeyVaultClientGetSecretOptions contains the optional parameters for the KeyVaultClient.GetSecret method.
type KeyVaultClientGetSecretOptions struct {
	// placeholder for future optional parameters
}

// KeyVaultClientGetSecretVersionsOptions contains the optional parameters for the KeyVaultClient.NewGetSecretVersionsPager
// method.
type KeyVaultClientGetSecretVersionsOptions struct {
	// Maximum number of results to return in a page. If not specified the service
	// will return up to 25 results.
	Maxresults *int32
}

// KeyVaultClientGetSecretsOptions contains the optional parameters for the KeyVaultClient.NewGetSecretsPager method.
type KeyVaultClientGetSecretsOptions struct {
	// Maximum number of results to return in a page. If not specified the service
	// will return up to 25 results.
	Maxresults *int32
}

// KeyVaultClientPurgeDeletedSecretOptions contains the optional parameters for the KeyVaultClient.PurgeDeletedSecret method.
type KeyVaultClientPurgeDeletedSecretOptions struct {
	// placeholder for future optional parameters
}

// KeyVaultClientRecoverDeletedSecretOptions contains the optional parameters for the KeyVaultClient.RecoverDeletedSecret
// method.
type KeyVaultClientRecoverDeletedSecretOptions struct {
	// placeholder for future optional parameters
}

// KeyVaultClientRestoreSecretOptions contains the optional parameters for the KeyVaultClient.RestoreSecret method.
type KeyVaultClientRestoreSecretOptions struct {
	// placeholder for future optional parameters
}

// KeyVaultClientSetSecretOptions contains the optional parameters for the KeyVaultClient.SetSecret method.
type KeyVaultClientSetSecretOptions struct {
	// placeholder for future optional parameters
}

// KeyVaultClientUpdateSecretOptions contains the optional parameters for the KeyVaultClient.UpdateSecret method.
type KeyVaultClientUpdateSecretOptions struct {
	// placeholder for future optional parameters
}
