// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See License.txt in the project root for license information.
// Code generated by Microsoft (R) Go Code Generator. DO NOT EDIT.

package azsecrets

// KeyVaultClientBackupSecretResponse contains the response from method KeyVaultClient.BackupSecret.
type KeyVaultClientBackupSecretResponse struct {
	// The backup secret result, containing the backup blob.
	BackupSecretResult
}

// KeyVaultClientDeleteSecretResponse contains the response from method KeyVaultClient.DeleteSecret.
type KeyVaultClientDeleteSecretResponse struct {
	// A Deleted Secret consisting of its previous id, attributes and its tags, as
	// well as information on when it will be purged.
	DeletedSecretBundle
}

// KeyVaultClientGetDeletedSecretResponse contains the response from method KeyVaultClient.GetDeletedSecret.
type KeyVaultClientGetDeletedSecretResponse struct {
	// A Deleted Secret consisting of its previous id, attributes and its tags, as
	// well as information on when it will be purged.
	DeletedSecretBundle
}

// KeyVaultClientGetDeletedSecretsResponse contains the response from method KeyVaultClient.NewGetDeletedSecretsPager.
type KeyVaultClientGetDeletedSecretsResponse struct {
	// Paged collection of DeletedSecretItem items
	PagedDeletedSecretItem
}

// KeyVaultClientGetSecretResponse contains the response from method KeyVaultClient.GetSecret.
type KeyVaultClientGetSecretResponse struct {
	// A secret consisting of a value, id and its attributes.
	SecretBundle
}

// KeyVaultClientGetSecretVersionsResponse contains the response from method KeyVaultClient.NewGetSecretVersionsPager.
type KeyVaultClientGetSecretVersionsResponse struct {
	// The secret list result.
	SecretListResult
}

// KeyVaultClientGetSecretsResponse contains the response from method KeyVaultClient.NewGetSecretsPager.
type KeyVaultClientGetSecretsResponse struct {
	// Paged collection of SecretItem items
	PagedSecretItem
}

// KeyVaultClientPurgeDeletedSecretResponse contains the response from method KeyVaultClient.PurgeDeletedSecret.
type KeyVaultClientPurgeDeletedSecretResponse struct {
	// placeholder for future response values
}

// KeyVaultClientRecoverDeletedSecretResponse contains the response from method KeyVaultClient.RecoverDeletedSecret.
type KeyVaultClientRecoverDeletedSecretResponse struct {
	// A secret consisting of a value, id and its attributes.
	SecretBundle
}

// KeyVaultClientRestoreSecretResponse contains the response from method KeyVaultClient.RestoreSecret.
type KeyVaultClientRestoreSecretResponse struct {
	// A secret consisting of a value, id and its attributes.
	SecretBundle
}

// KeyVaultClientSetSecretResponse contains the response from method KeyVaultClient.SetSecret.
type KeyVaultClientSetSecretResponse struct {
	// A secret consisting of a value, id and its attributes.
	SecretBundle
}

// KeyVaultClientUpdateSecretResponse contains the response from method KeyVaultClient.UpdateSecret.
type KeyVaultClientUpdateSecretResponse struct {
	// A secret consisting of a value, id and its attributes.
	SecretBundle
}
